# Generated by Django 5.0 on 2023-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='This product is verified by the flipkart organization. Feel free to buy this one. This is default title.', max_length=200)),
                ('product_prophile', models.ImageField(upload_to='static/productprophile images/')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('features', models.TextField(default='', max_length=2000)),
                ('stars', models.CharField(default='3', max_length=1)),
                ('units', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
