# Generated by Django 5.0 on 2023-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productdetails_product_name_reviewdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='features',
        ),
    ]
