# Generated by Django 5.0 on 2023-12-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_productdetails_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
